use iced::{color, Color, Font};

#[derive(Debug, Clone, Copy)]
#[allow(dead_code)]
pub struct ThemeTokens {
    pub colors: ColorTokens,
    pub typography: TypographyTokens,
    pub spacing: SpacingTokens,
    pub sizes: SizeTokens,
    pub radius: RadiusTokens,
}

#[derive(Debug, Clone, Copy)]
#[allow(dead_code)]
pub struct ColorTokens {
    pub background: Color,
    pub surface: Color,
    pub surface_elevated: Color,
    pub surface_hover: Color,
    pub surface_selected: Color,
    pub surface_active: Color,
    pub panel: Color,
    pub border: Color,
    pub border_subtle: Color,
    pub text: Color,
    pub text_muted: Color,
    pub text_disabled: Color,
    pub accent: Color,
    pub accent_hover: Color,
    pub accent_soft: Color,
    pub success: Color,
    pub warning: Color,
    pub error: Color,
    pub selected_text: Color,
    pub editor_background: Color,
    pub editor_row_odd: Color,
    pub editor_row_even: Color,
    pub editor_gutter: Color,
    pub editor_current_line: Color,
    pub editor_selection: Color,
    pub grid_header: Color,
    pub grid_row_odd: Color,
    pub grid_row_even: Color,
    pub grid_gutter: Color,
    pub grid_separator: Color,
    pub menu_background: Color,
    pub overlay_backdrop: Color,
}

#[derive(Debug, Clone, Copy)]
#[allow(dead_code)]
pub struct TypographyTokens {
    pub ui_font: Font,
    pub mono_font: Font,
    pub font_size_body: u32,
    pub font_size_small: u32,
    pub font_size_label: u32,
    pub font_size_heading: u32,
    pub font_size_editor: u32,
    pub font_size_editor_line_number: u32,
    pub font_size_grid: u32,
    pub font_size_menu: u32,
}

#[derive(Debug, Clone, Copy)]
pub struct SpacingTokens {
    pub xxs: f32,
    pub xs: f32,
    pub sm: f32,
    pub md: f32,
    pub lg: f32,
    pub xl: f32,
    pub xxl: f32,
}

#[derive(Debug, Clone, Copy)]
#[allow(dead_code)]
pub struct SizeTokens {
    pub activity_bar_width: f32,
    pub activity_button_size: f32,
    pub activity_icon_size: f32,
    pub toolbar_height: f32,
    pub toolbar_button_width: f32,
    pub toolbar_button_height: f32,
    pub toolbar_icon_size: f32,
    pub toolbar_search_width: f32,
    pub tab_height: f32,
    pub tab_button_height: f32,
    pub tab_close_width: f32,
    pub tab_icon_size: f32,
    pub tab_underline_height: f32,
    pub editor_line_height_ratio: f32,
    pub editor_gutter_width: f32,
    pub editor_gutter_line_width: f32,
    pub data_grid_row_height: f32,
    pub data_grid_header_height: f32,
    pub data_grid_gutter_width: f32,
    pub sidebar_default_width: f32,
    pub inspector_default_width: f32,
    pub schema_default_width: f32,
    pub sql_editor_default_height: f32,
    pub sidebar_min_width: f32,
    pub sidebar_max_width: f32,
    pub inspector_min_width: f32,
    pub inspector_max_width: f32,
    pub schema_min_width: f32,
    pub schema_max_width: f32,
    pub sql_editor_min_height: f32,
    pub sql_editor_max_height: f32,
    pub splitter_hit_area: f32,
    pub menu_bar_height: f32,
    pub menu_width: f32,
    pub menu_top_offset: f32,
    pub search_overlay_width: f32,
    pub search_overlay_height: f32,
    pub search_results_height: f32,
    pub dialog_width: f32,
    pub divider_width: f32,
    pub divider_height: f32,
}

#[derive(Debug, Clone, Copy)]
pub struct RadiusTokens {
    pub small: f32,
    pub medium: f32,
    pub large: f32,
}

pub const SPACING: SpacingTokens = SpacingTokens {
    xxs: 2.0,
    xs: 4.0,
    sm: 8.0,
    md: 12.0,
    lg: 16.0,
    xl: 20.0,
    xxl: 24.0,
};

pub const TYPOGRAPHY: TypographyTokens = TypographyTokens {
    ui_font: Font::DEFAULT,
    mono_font: Font::MONOSPACE,
    font_size_body: 13,
    font_size_small: 12,
    font_size_label: 11,
    font_size_heading: 15,
    font_size_editor: 14,
    font_size_editor_line_number: 14,
    font_size_grid: 13,
    font_size_menu: 13,
};

pub const SIZES: SizeTokens = SizeTokens {
    activity_bar_width: 56.0,
    activity_button_size: 40.0,
    activity_icon_size: 20.0,
    toolbar_height: 50.0,
    toolbar_button_width: 32.0,
    toolbar_button_height: 30.0,
    toolbar_icon_size: 16.0,
    toolbar_search_width: 250.0,
    tab_height: 38.0,
    tab_button_height: 30.0,
    tab_close_width: 24.0,
    tab_icon_size: 13.0,
    tab_underline_height: 2.0,
    editor_line_height_ratio: 1.45,
    editor_gutter_width: 64.0,
    editor_gutter_line_width: 42.0,
    data_grid_row_height: 28.0,
    data_grid_header_height: 30.0,
    data_grid_gutter_width: 42.0,
    sidebar_default_width: 272.0,
    inspector_default_width: 300.0,
    schema_default_width: 286.0,
    sql_editor_default_height: 285.0,
    sidebar_min_width: 220.0,
    sidebar_max_width: 420.0,
    inspector_min_width: 240.0,
    inspector_max_width: 420.0,
    schema_min_width: 230.0,
    schema_max_width: 430.0,
    sql_editor_min_height: 180.0,
    sql_editor_max_height: 520.0,
    splitter_hit_area: 7.0,
    menu_bar_height: 32.0,
    menu_width: 228.0,
    menu_top_offset: 34.0,
    search_overlay_width: 680.0,
    search_overlay_height: 500.0,
    search_results_height: 330.0,
    dialog_width: 430.0,
    divider_width: 1.0,
    divider_height: 22.0,
};

pub const RADIUS: RadiusTokens = RadiusTokens {
    small: 4.0,
    medium: 6.0,
    large: 8.0,
};

pub const DARK: ThemeTokens = ThemeTokens {
    colors: ColorTokens {
        background: color!(0x090d14),
        surface: color!(0x0f151f),
        surface_elevated: color!(0x151d2a),
        surface_hover: color!(0x1b2534),
        surface_selected: color!(0x241d3f),
        surface_active: color!(0x202b3b),
        panel: color!(0x101720),
        border: color!(0x253144),
        border_subtle: color!(0x1a2433),
        text: color!(0xe8eef8),
        text_muted: color!(0xa4afc1),
        text_disabled: color!(0x6f7a8d),
        accent: color!(0x9b7cff),
        accent_hover: color!(0xb39aff),
        accent_soft: color!(0x282044),
        success: color!(0x43d18b),
        warning: color!(0xf0a742),
        error: color!(0xf26464),
        selected_text: color!(0xf7f3ff),
        editor_background: color!(0x0b1018),
        editor_row_odd: color!(0x0b1018),
        editor_row_even: color!(0x0d121b),
        editor_gutter: color!(0x111925),
        editor_current_line: color!(0x121a27),
        editor_selection: color!(0x282044),
        grid_header: color!(0x151d2a),
        grid_row_odd: color!(0x0b1018),
        grid_row_even: color!(0x0f151f),
        grid_gutter: color!(0x111925),
        grid_separator: color!(0x182231),
        menu_background: color!(0x151d2a),
        overlay_backdrop: Color {
            a: 0.34,
            ..Color::BLACK
        },
    },
    typography: TYPOGRAPHY,
    spacing: SPACING,
    sizes: SIZES,
    radius: RADIUS,
};

pub const LIGHT: ThemeTokens = ThemeTokens {
    colors: ColorTokens {
        background: color!(0xf4f6fb),
        surface: color!(0xfafbfd),
        surface_elevated: color!(0xffffff),
        surface_hover: color!(0xeef2f8),
        surface_selected: color!(0xeee8ff),
        surface_active: color!(0xe5eaf3),
        panel: color!(0xf9fafc),
        border: color!(0xd8deea),
        border_subtle: color!(0xe8ecf3),
        text: color!(0x182030),
        text_muted: color!(0x657084),
        text_disabled: color!(0x9aa3b3),
        accent: color!(0x6f45e8),
        accent_hover: color!(0x5f35d9),
        accent_soft: color!(0xeee8ff),
        success: color!(0x147a4d),
        warning: color!(0xa96813),
        error: color!(0xc43f3f),
        selected_text: color!(0x241452),
        editor_background: color!(0xffffff),
        editor_row_odd: color!(0xffffff),
        editor_row_even: color!(0xfafbfd),
        editor_gutter: color!(0xf1f3f8),
        editor_current_line: color!(0xf4f6fb),
        editor_selection: color!(0xeee8ff),
        grid_header: color!(0xffffff),
        grid_row_odd: color!(0xffffff),
        grid_row_even: color!(0xf8f9fc),
        grid_gutter: color!(0xf1f3f8),
        grid_separator: color!(0xe4e8f0),
        menu_background: color!(0xffffff),
        overlay_backdrop: Color {
            a: 0.22,
            ..color!(0xd8deea)
        },
    },
    typography: TYPOGRAPHY,
    spacing: SPACING,
    sizes: SIZES,
    radius: RADIUS,
};
