use iced::{color, Color, Font};

#[derive(Debug, Clone, Copy)]
#[allow(dead_code)]
pub struct ThemeTokens {
    pub colors: ColorTokens,
    pub typography: TypographyTokens,
    pub spacing: SpacingTokens,
    pub sizes: SizeTokens,
    pub radius: RadiusTokens,
}

#[derive(Debug, Clone, Copy)]
#[allow(dead_code)]
pub struct ColorTokens {
    pub app_background: Color,
    pub activity_bar_background: Color,
    pub sidebar_background: Color,
    pub content_background: Color,
    pub inspector_background: Color,
    pub top_bar_background: Color,
    pub status_bar_background: Color,
    pub background: Color,
    pub surface: Color,
    pub surface_elevated: Color,
    pub surface_hover: Color,
    pub surface_pressed: Color,
    pub surface_selected: Color,
    pub surface_active: Color,
    pub panel: Color,
    pub border_subtle: Color,
    pub border: Color,
    pub border_strong: Color,
    pub focus_ring: Color,
    pub text: Color,
    pub text_muted: Color,
    pub text_disabled: Color,
    pub text_inverse: Color,
    pub accent: Color,
    pub accent_hover: Color,
    pub accent_pressed: Color,
    pub accent_soft: Color,
    pub accent_border: Color,
    pub accent_text: Color,
    pub success: Color,
    pub success_soft: Color,
    pub warning: Color,
    pub warning_soft: Color,
    pub error: Color,
    pub error_soft: Color,
    pub info: Color,
    pub info_soft: Color,
    pub selected_text: Color,
    pub editor_background: Color,
    pub editor_gutter_background: Color,
    pub editor_zebra: Color,
    pub editor_row_odd: Color,
    pub editor_row_even: Color,
    pub editor_gutter: Color,
    pub editor_current_line: Color,
    pub editor_selection: Color,
    pub preview_background: Color,
    pub preview_text: Color,
    pub preview_code_background: Color,
    pub preview_quote_border: Color,
    pub preview_link: Color,
    pub grid_header: Color,
    pub grid_row_odd: Color,
    pub grid_row_even: Color,
    pub grid_gutter: Color,
    pub grid_separator: Color,
    pub menu_background: Color,
    pub overlay_backdrop: Color,
    pub graph_background: Color,
    pub graph_toolbar_background: Color,
    pub graph_toolbar_border: Color,
    pub graph_toolbar_button: Color,
    pub graph_toolbar_button_hover: Color,
    pub graph_toolbar_button_active: Color,
    pub graph_toolbar_button_disabled: Color,
    pub graph_zoom_badge_background: Color,
    pub graph_zoom_badge_text: Color,
    pub graph_canvas_grid: Color,
    pub graph_node: Color,
    pub graph_node_hover: Color,
    pub graph_node_selected: Color,
    pub graph_node_border: Color,
    pub graph_node_shadow: Color,
    pub graph_edge: Color,
    pub graph_edge_active: Color,
    pub graph_unresolved: Color,
    pub graph_ambiguous: Color,
}

#[derive(Debug, Clone, Copy)]
#[allow(dead_code)]
pub struct TypographyTokens {
    pub ui_font: Font,
    pub mono_font: Font,
    pub font_size_body: u32,
    pub font_size_small: u32,
    pub font_size_label: u32,
    pub font_size_heading: u32,
    pub font_size_editor: u32,
    pub font_size_editor_line_number: u32,
    pub font_size_grid: u32,
    pub font_size_menu: u32,
}

#[derive(Debug, Clone, Copy)]
pub struct SpacingTokens {
    pub xxs: f32,
    pub xs: f32,
    pub sm: f32,
    pub md: f32,
    pub lg: f32,
    pub xl: f32,
    pub xxl: f32,
}

#[derive(Debug, Clone, Copy)]
#[allow(dead_code)]
pub struct SizeTokens {
    pub control_height_small: f32,
    pub control_height_medium: f32,
    pub control_height_large: f32,
    pub icon_slot_small: f32,
    pub icon_slot_medium: f32,
    pub icon_slot_large: f32,
    pub activity_bar_width: f32,
    pub activity_button_size: f32,
    pub activity_icon_size: f32,
    pub toolbar_height: f32,
    pub toolbar_button_width: f32,
    pub toolbar_button_height: f32,
    pub toolbar_icon_size: f32,
    pub toolbar_search_width: f32,
    pub tab_height: f32,
    pub tab_button_height: f32,
    pub tab_close_width: f32,
    pub tab_icon_size: f32,
    pub tab_underline_height: f32,
    pub document_header_height: f32,
    pub editor_line_height_ratio: f32,
    pub editor_gutter_width: f32,
    pub editor_gutter_line_width: f32,
    pub data_grid_row_height: f32,
    pub data_grid_header_height: f32,
    pub data_grid_gutter_width: f32,
    pub sidebar_default_width: f32,
    pub inspector_default_width: f32,
    pub schema_default_width: f32,
    pub sql_editor_default_height: f32,
    pub sidebar_min_width: f32,
    pub sidebar_max_width: f32,
    pub inspector_min_width: f32,
    pub inspector_max_width: f32,
    pub schema_min_width: f32,
    pub schema_max_width: f32,
    pub sql_editor_min_height: f32,
    pub sql_editor_max_height: f32,
    pub splitter_hit_area: f32,
    pub menu_bar_height: f32,
    pub menu_width: f32,
    pub menu_top_offset: f32,
    pub menu_item_height: f32,
    pub menu_padding_y: f32,
    pub menu_padding_x: f32,
    pub menu_popup_padding: f32,
    pub search_overlay_width: f32,
    pub search_overlay_height: f32,
    pub search_results_height: f32,
    pub dialog_width: f32,
    pub divider_width: f32,
    pub divider_height: f32,
    pub graph_node_width: f32,
    pub graph_node_height: f32,
    pub graph_toolbar_button_size: f32,
    pub graph_zoom_badge_width: f32,
    pub graph_grid_step: f32,
    pub graph_node_font_size: u32,
    pub graph_edge_label_font_size: u32,
}

#[derive(Debug, Clone, Copy)]
pub struct RadiusTokens {
    pub small: f32,
    pub medium: f32,
    pub large: f32,
}

pub const SPACING: SpacingTokens = SpacingTokens {
    xxs: 2.0,
    xs: 4.0,
    sm: 8.0,
    md: 12.0,
    lg: 16.0,
    xl: 20.0,
    xxl: 24.0,
};

pub const TYPOGRAPHY: TypographyTokens = TypographyTokens {
    ui_font: Font::DEFAULT,
    mono_font: Font::MONOSPACE,
    font_size_body: 15,
    font_size_small: 12,
    font_size_label: 12,
    font_size_heading: 18,
    font_size_editor: 16,
    font_size_editor_line_number: 14,
    font_size_grid: 13,
    font_size_menu: 14,
};

pub const SIZES: SizeTokens = SizeTokens {
    control_height_small: 30.0,
    control_height_medium: 36.0,
    control_height_large: 40.0,
    icon_slot_small: 18.0,
    icon_slot_medium: 20.0,
    icon_slot_large: 24.0,
    activity_bar_width: 58.0,
    activity_button_size: 38.0,
    activity_icon_size: 22.0,
    toolbar_height: 58.0,
    toolbar_button_width: 36.0,
    toolbar_button_height: 36.0,
    toolbar_icon_size: 17.0,
    toolbar_search_width: 470.0,
    tab_height: 48.0,
    tab_button_height: 34.0,
    tab_close_width: 24.0,
    tab_icon_size: 13.0,
    tab_underline_height: 2.0,
    document_header_height: 76.0,
    editor_line_height_ratio: 1.62,
    editor_gutter_width: 62.0,
    editor_gutter_line_width: 38.0,
    data_grid_row_height: 27.0,
    data_grid_header_height: 29.0,
    data_grid_gutter_width: 42.0,
    sidebar_default_width: 292.0,
    inspector_default_width: 292.0,
    schema_default_width: 286.0,
    sql_editor_default_height: 285.0,
    sidebar_min_width: 220.0,
    sidebar_max_width: 420.0,
    inspector_min_width: 260.0,
    inspector_max_width: 360.0,
    schema_min_width: 230.0,
    schema_max_width: 430.0,
    sql_editor_min_height: 180.0,
    sql_editor_max_height: 520.0,
    splitter_hit_area: 8.0,
    menu_bar_height: 58.0,
    menu_width: 228.0,
    menu_top_offset: 58.0,
    menu_item_height: 24.0,
    menu_padding_y: 0.0,
    menu_padding_x: 10.0,
    menu_popup_padding: 4.0,
    search_overlay_width: 680.0,
    search_overlay_height: 500.0,
    search_results_height: 330.0,
    dialog_width: 430.0,
    divider_width: 1.0,
    divider_height: 22.0,
    graph_node_width: 156.0,
    graph_node_height: 62.0,
    graph_toolbar_button_size: 30.0,
    graph_zoom_badge_width: 56.0,
    graph_grid_step: 30.0,
    graph_node_font_size: 13,
    graph_edge_label_font_size: 11,
};

pub const RADIUS: RadiusTokens = RadiusTokens {
    small: 6.0,
    medium: 8.0,
    large: 12.0,
};

pub const DARK: ThemeTokens = ThemeTokens {
    colors: ColorTokens {
        app_background: color!(0x090d14),
        activity_bar_background: color!(0x0b1018),
        sidebar_background: color!(0x0f151f),
        content_background: color!(0x0b1018),
        inspector_background: color!(0x0f151f),
        top_bar_background: color!(0x0d131c),
        status_bar_background: color!(0x0d131c),
        background: color!(0x090d14),
        surface: color!(0x111925),
        surface_elevated: color!(0x151d2a),
        surface_hover: color!(0x1b2534),
        surface_pressed: color!(0x202b3b),
        surface_selected: color!(0x282044),
        surface_active: color!(0x202b3b),
        panel: color!(0x0f151f),
        border_subtle: color!(0x182231),
        border: color!(0x223048),
        border_strong: color!(0x394760),
        focus_ring: color!(0x9b7cff),
        text: color!(0xe8eef8),
        text_muted: color!(0xa7b1c2),
        text_disabled: color!(0x6f7a8d),
        text_inverse: color!(0x0b1018),
        accent: color!(0x8b5cf6),
        accent_hover: color!(0xa78bfa),
        accent_pressed: color!(0x7c3aed),
        accent_soft: color!(0x2b2147),
        accent_border: color!(0x5b45a5),
        accent_text: color!(0xcbb9ff),
        success: color!(0x43d18b),
        success_soft: color!(0x123225),
        warning: color!(0xf0a742),
        warning_soft: color!(0x332514),
        error: color!(0xf26464),
        error_soft: color!(0x351a20),
        info: color!(0x6ea8ff),
        info_soft: color!(0x15263f),
        selected_text: color!(0xf7f3ff),
        editor_background: color!(0x0b1018),
        editor_gutter_background: color!(0x101720),
        editor_zebra: color!(0x0c1119),
        editor_row_odd: color!(0x0b1018),
        editor_row_even: color!(0x0c1119),
        editor_gutter: color!(0x101720),
        editor_current_line: color!(0x141c29),
        editor_selection: color!(0x302451),
        preview_background: color!(0x0b1018),
        preview_text: color!(0xe8eef8),
        preview_code_background: color!(0x151d2a),
        preview_quote_border: color!(0x9b7cff),
        preview_link: color!(0xb39aff),
        grid_header: color!(0x151d2a),
        grid_row_odd: color!(0x0b1018),
        grid_row_even: color!(0x0f151f),
        grid_gutter: color!(0x111925),
        grid_separator: color!(0x182231),
        menu_background: color!(0x151d2a),
        overlay_backdrop: Color {
            a: 0.34,
            ..Color::BLACK
        },
        graph_background: color!(0x090d14),
        graph_toolbar_background: color!(0x101720),
        graph_toolbar_border: color!(0x1f2a3b),
        graph_toolbar_button: color!(0x121a26),
        graph_toolbar_button_hover: color!(0x1b2534),
        graph_toolbar_button_active: color!(0x282044),
        graph_toolbar_button_disabled: color!(0x0d131c),
        graph_zoom_badge_background: color!(0x0d131c),
        graph_zoom_badge_text: color!(0xa4afc1),
        graph_canvas_grid: color!(0x1a2433),
        graph_node: color!(0x121a26),
        graph_node_hover: color!(0x1b2534),
        graph_node_selected: color!(0x282044),
        graph_node_border: color!(0x31405a),
        graph_node_shadow: Color {
            a: 0.20,
            ..Color::BLACK
        },
        graph_edge: color!(0x526075),
        graph_edge_active: color!(0xb39aff),
        graph_unresolved: color!(0xf0a742),
        graph_ambiguous: color!(0xf26464),
    },
    typography: TYPOGRAPHY,
    spacing: SPACING,
    sizes: SIZES,
    radius: RADIUS,
};

pub const LIGHT: ThemeTokens = ThemeTokens {
    colors: ColorTokens {
        app_background: color!(0xf4f6fb),
        activity_bar_background: color!(0xf8f9fe),
        sidebar_background: color!(0xfbfcff),
        content_background: color!(0xffffff),
        inspector_background: color!(0xfbfcff),
        top_bar_background: color!(0xf8f9fe),
        status_bar_background: color!(0xf8f9fe),
        background: color!(0xf4f6fb),
        surface: color!(0xf8f9fe),
        surface_elevated: color!(0xffffff),
        surface_hover: color!(0xf0f3f9),
        surface_pressed: color!(0xe6ebf4),
        surface_selected: color!(0xf0eaff),
        surface_active: color!(0xe8edf6),
        panel: color!(0xfbfcff),
        border_subtle: color!(0xecf0f7),
        border: color!(0xdfe5f0),
        border_strong: color!(0xc7d0df),
        focus_ring: color!(0x7c3aed),
        text: color!(0x182030),
        text_muted: color!(0x657084),
        text_disabled: color!(0x9aa3b3),
        text_inverse: color!(0xffffff),
        accent: color!(0x7f56f0),
        accent_hover: color!(0x7048df),
        accent_pressed: color!(0x5f35c8),
        accent_soft: color!(0xf1eaff),
        accent_border: color!(0xdfd2ff),
        accent_text: color!(0x6c3fe0),
        success: color!(0x147a4d),
        success_soft: color!(0xe8f7ef),
        warning: color!(0xa96813),
        warning_soft: color!(0xfff4de),
        error: color!(0xc43f3f),
        error_soft: color!(0xffecec),
        info: color!(0x2563eb),
        info_soft: color!(0xeaf1ff),
        selected_text: color!(0x2d145f),
        editor_background: color!(0xffffff),
        editor_gutter_background: color!(0xf8f9fd),
        editor_zebra: color!(0xfdfdff),
        editor_row_odd: color!(0xffffff),
        editor_row_even: color!(0xfdfdff),
        editor_gutter: color!(0xf8f9fd),
        editor_current_line: color!(0xf5f7fb),
        editor_selection: color!(0xf0eaff),
        preview_background: color!(0xffffff),
        preview_text: color!(0x182030),
        preview_code_background: color!(0xf1f3f8),
        preview_quote_border: color!(0x6f45e8),
        preview_link: color!(0x5f35d9),
        grid_header: color!(0xffffff),
        grid_row_odd: color!(0xffffff),
        grid_row_even: color!(0xf8f9fc),
        grid_gutter: color!(0xf1f3f8),
        grid_separator: color!(0xe4e8f0),
        menu_background: color!(0xffffff),
        overlay_backdrop: Color {
            a: 0.22,
            ..color!(0xd8deea)
        },
        graph_background: color!(0xf4f6fb),
        graph_toolbar_background: color!(0xffffff),
        graph_toolbar_border: color!(0xdfe4ee),
        graph_toolbar_button: color!(0xf8f9fc),
        graph_toolbar_button_hover: color!(0xeef2f8),
        graph_toolbar_button_active: color!(0xeee8ff),
        graph_toolbar_button_disabled: color!(0xf1f3f8),
        graph_zoom_badge_background: color!(0xf1f3f8),
        graph_zoom_badge_text: color!(0x657084),
        graph_canvas_grid: color!(0xdfe4ee),
        graph_node: color!(0xffffff),
        graph_node_hover: color!(0xeef2f8),
        graph_node_selected: color!(0xeee8ff),
        graph_node_border: color!(0xc7cfdd),
        graph_node_shadow: Color {
            a: 0.13,
            ..color!(0x4b5565)
        },
        graph_edge: color!(0x8791a3),
        graph_edge_active: color!(0x6f45e8),
        graph_unresolved: color!(0xa96813),
        graph_ambiguous: color!(0xc43f3f),
    },
    typography: TYPOGRAPHY,
    spacing: SPACING,
    sizes: SIZES,
    radius: RADIUS,
};
