use std::{path::PathBuf, time::Instant};

use flokin_core::{
    BulkEditOperationKind, BulkEditValueType, CollectionPanel, EditorViewMode, ExplorerNodeId,
    GraphNodeId, HealthFilter, MutationHistoryEntry, ScanResult, SqlCatalog, SqlError,
    SqlExplorerMode, SqlQueryResult, SqlWritePlan, WorkspaceUpdate,
};
use iced::{
    keyboard,
    widget::{markdown, text_editor},
    window,
};

use crate::i18n::AppLanguage;
use crate::services::file_watcher::WatcherMessage;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MenuId {
    File,
    View,
    Navigate,
    Data,
    Help,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MenuAction {
    OpenFolder,
    Reindex,
    ToggleTheme,
    ToggleLeftSidebar,
    ToggleRightSidebar,
    Explorer,
    Data,
    Graph,
    Health,
    SqlExplorer,
    Settings,
    Search,
    ExecuteSql,
    History,
    About,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AppMode {
    Files,
    Data,
    Graph,
    Health,
    Sql,
    Settings,
    History,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SplitterKind {
    LeftSidebar,
    Inspector,
    SqlSchema,
    SqlEditor,
    MarkdownPreview,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Message {
    AppModeSelected(AppMode),
    #[allow(dead_code)]
    ExplorerNodeToggled(ExplorerNodeId),
    OpenFolder,
    FolderSelected(Option<PathBuf>),
    ScanCompleted(u64, PathBuf, Result<ScanResult, String>),
    ReindexWorkspace,
    WorkspaceWatcher(WatcherMessage),
    WorkspaceUpdateCompleted(u64, PathBuf, Result<WorkspaceUpdate, String>),
    CollectionSelected(String),
    CollectionPanelSelected(CollectionPanel),
    SchemaFieldSelected {
        collection_id: String,
        field_name: String,
    },
    HealthFilterSelected(HealthFilter),
    HealthQueryChanged(String),
    HealthIssueSelected(String),
    HealthIssueOpened(String),
    SchemaCreateRequested,
    SchemaCreateCanceled,
    SchemaCreateConfirmed,
    SchemaCreateCompleted(Result<PathBuf, String>),
    SchemaOpenRequested,
    TableHeaderSelected(String),
    BulkSelectionToggled(PathBuf),
    BulkSelectAllVisible(bool),
    BulkSelectionCleared,
    BulkEditOpened,
    BulkEditCanceled,
    BulkEditBackToConfigure,
    BulkNewPropertyRequested,
    BulkOperationSelected(BulkEditOperationKind),
    BulkPropertySelected(String),
    BulkNewPropertyChanged(String),
    BulkValueTypeSelected(BulkEditValueType),
    BulkValueChanged(String),
    BulkBoolValueSelected(bool),
    BulkPreviewRequested,
    BulkApplyRequested,
    BulkApplyCompleted(Result<(Vec<PathBuf>, usize, Option<String>), String>),
    MarkdownSelected(PathBuf),
    GraphFitRequested,
    GraphFocusSelected,
    GraphZoomIn,
    GraphZoomOut,
    GraphZoomReset,
    GraphViewportChanged(f32, f32),
    GraphNodeSelected(GraphNodeId),
    GraphNodeOpened(GraphNodeId),
    GraphPanBy(f32, f32),
    GraphZoomAt {
        x: f32,
        y: f32,
        delta: f32,
    },
    GraphNodeDragged {
        node: GraphNodeId,
        dx: f32,
        dy: f32,
    },
    EditorTabSelected(PathBuf),
    EditorTabCloseRequested(PathBuf),
    MarkdownEditorAction(text_editor::Action),
    EditorViewModeSelected(EditorViewMode),
    MarkdownLinkClicked(markdown::Uri),
    EditorSaveRequested,
    EditorSaveCompleted(PathBuf, String, Result<(), String>),
    EditorCloseActiveRequested,
    EditorDialogCancel,
    EditorDialogDiscard,
    EditorDialogSave,
    EditorExternalReload,
    EditorExternalKeep,
    WindowCloseRequested(window::Id),
    WindowFocused(bool),
    SearchOpened,
    SearchClosed,
    SearchQueryChanged(String),
    SearchDebounceElapsed(Instant),
    SearchNext,
    SearchPrevious,
    SearchActivated,
    SearchResultSelected(PathBuf),
    SqlExplorerOpened,
    SqlSchemaTableToggled(String),
    SqlEditorAction(text_editor::Action),
    SqlCompletionRequested,
    SqlCompletionNext,
    SqlCompletionPrevious,
    SqlCompletionAccepted,
    SqlCompletionSelected(usize),
    SqlCompletionClosed,
    SqlModeSelected(SqlExplorerMode),
    SqlExecute,
    SqlProjectionCompleted(u64, PathBuf, Result<SqlCatalog, SqlError>),
    SqlQueryCompleted(Result<SqlQueryResult, SqlError>),
    SqlUpdatePreviewCompleted(Result<SqlWritePlan, SqlError>),
    SqlUpdateBackToEditor,
    SqlUpdatePreviewCanceled,
    SqlUpdateApplyRequested,
    SqlUpdateApplyCompleted(Result<(Vec<PathBuf>, usize, Option<String>), String>),
    HistoryLoaded(PathBuf, Result<Vec<MutationHistoryEntry>, String>),
    HistoryEntrySelected(String),
    HistoryUndoRequested,
    HistoryUndoPreviewCanceled,
    HistoryUndoApplyRequested,
    HistoryUndoApplyCompleted(Result<(Vec<PathBuf>, usize, Option<String>), String>),
    HistoryClearRequested,
    HistoryClearCanceled,
    HistoryClearConfirmed,
    HistoryClearCompleted(Result<(), String>),
    KeyboardEvent(keyboard::Event),
    ThemeToggled,
    ThemeSelected(bool),
    ThemePersisted(Result<(), String>),
    LanguageSelected(AppLanguage),
    LanguagePersisted(Result<(), String>),
    MenuToggled(MenuId),
    MenuHovered(MenuId),
    MenuAction(MenuAction),
    MenuClosed,
    AboutClosed,
    SplitterPressed(SplitterKind, f32),
    SplitterMoved(f32, f32),
    SplitterReleased,
    ToggleLeftSidebar,
    ToggleRightSidebar,
    ResetLayout,
    MockAction,
}
